[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.15"
verbosity = 1
via_ir = false
remappings = [
    'utils/=utils',
    '/=src',
    'libraries/=src/libraries',
    'interfaces/=src/interfaces',
    'cauldrons/=src/cauldrons',
    'swappers/=src/swappers',
    'oracles/=src/oracles',
    'strategies/=src/strategies',
    'withdrawers/=src/withdrawers',
]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config