[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.15"
verbosity = 2
remappings = [
    'utils/=utils/'
]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config