name: Foundry

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FOUNDRY_PROFILE: ci
  MAINNET_RPC_URL: https://eth-mainnet.g.alchemy.com/v2/RCpsVH9b5GAwZonxxZOgJ6ouum3h4Oys
  OPTIMISM_RPC_URL: https://mainnet.optimism.io
  BSC_RPC_URL: https://binance.nodereal.io
  FANTOM_RPC_URL: https://rpc2.fantom.network
  ARBITRUM_RPC_URL: https://1rpc.io/arb
  POLYGON_RPC_URL: https://polygon.llamarpc.com
  AVALANCHE_RPC_URL: https://api.avax.network/ext/bc/C/rpc

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vv
        id: test
